// Single source of truth for FertaFind's indexable content pages (guides,
// comparisons, methodology) and the generated sitemap.
//
// Adding a page here automatically feeds: canonical + Open Graph metadata,
// Article/WebPage + BreadcrumbList structured data, the /resources hub listing,
// and public/sitemap.xml (generated by buildSitemapXml and enforced by tests).
//
// This module is intentionally framework-free (no React / @/ alias / import.meta)
// so it can be unit-tested directly with `node --test`.

import {
  SITE_URL,
  SITE_NAME,
  DEFAULT_OG_IMAGE,
  canonicalUrl,
  jsonLdScript,
  breadcrumbLd,
  PAGES,
  type MetaEntry,
  type LinkEntry,
} from "./seo.ts";
import { publicSupplierSlugs, supplierPath } from "./suppliers.ts";
import { DEFAULT_LOCALE, SUPPORTED_LOCALES, localePath, type Locale } from "./i18n.ts";
import { localizedHead } from "./seo-i18n.ts";

/** A verifiable, external source shown beside the claims it supports. */
export interface Source {
  /** Human-readable title of the specific page/report. */
  label: string;
  /** The organisation that publishes it. */
  publisher: string;
  /** Absolute https URL. */
  url: string;
  /** Publication or review date shown on the source, if stated. */
  date?: string;
  /** ISO date this source was last checked by us. */
  accessed: string;
}

export type ContentSection = "guide" | "comparison" | "methodology";

export interface ContentPage {
  /** Full, descriptive path, e.g. "/guides/cost-per-pound-of-nitrogen". */
  slug: string;
  section: ContentSection;
  /** <title> */
  title: string;
  /** The single, visible <h1>. */
  h1: string;
  /** meta description (also used in the /resources listing). */
  description: string;
  ogTitle: string;
  ogDescription: string;
  /** ISO date, e.g. "2026-07-22" — rendered as "Last updated …" and used in JSON-LD. */
  lastUpdated: string;
  /** Structured-data type appropriate to the page. */
  structuredData: "Article" | "WebPage";
  /** Breadcrumb trail from Home to this page (paths are canonicalised). */
  breadcrumb: Array<{ name: string; path: string }>;
  /** Sources cited on the page. Never empty. */
  sources: Source[];
}

const ACCESSED = "2026-07-22";

// ---------------------------------------------------------------------------
// Verified sources (each URL was checked; grades/facts confirmed against the
// cited page). Illustrative dollar figures used in the page bodies are labelled
// as examples and are never presented as data from these sources.
// ---------------------------------------------------------------------------
const SRC = {
  ersFup: {
    label: "Fertilizer Use and Price",
    publisher: "USDA Economic Research Service (ERS)",
    url: "https://www.ers.usda.gov/data-products/fertilizer-use-and-price",
    date: "Updated December 30, 2025",
    accessed: ACCESSED,
  },
  ersFupDocs: {
    label: "Fertilizer Use and Price — Documentation and Data Sources",
    publisher: "USDA Economic Research Service (ERS)",
    url: "https://www.ers.usda.gov/data-products/fertilizer-use-and-price/documentation-and-data-sources",
    accessed: ACCESSED,
  },
  amsMarketNews: {
    label: "USDA Market News",
    publisher: "USDA Agricultural Marketing Service (AMS)",
    url: "https://www.ams.usda.gov/market-news",
    accessed: ACCESSED,
  },
  amsPricing: {
    label: "Pricing & Market Data",
    publisher: "USDA Agricultural Marketing Service (AMS)",
    url: "https://www.ams.usda.gov/resources/pricing-market-data",
    accessed: ACCESSED,
  },
  umnPhosphorus: {
    label: "Understanding phosphorus fertilizers",
    publisher: "University of Minnesota Extension",
    url: "https://extension.umn.edu/phosphorus-and-potassium/understanding-phosphorus-fertilizers",
    date: "Reviewed 2018",
    accessed: ACCESSED,
  },
  umnPhosphorusBlog: {
    label: "Phosphorus fertilizer sources: What are the differences?",
    publisher: "University of Minnesota Extension",
    url: "https://blog-crop-news.extension.umn.edu/2023/10/confused-about-differences-in.html",
    date: "October 2023",
    accessed: ACCESSED,
  },
  umnUrea: {
    label: "Fertilizer urea",
    publisher: "University of Minnesota Extension",
    url: "https://extension.umn.edu/nitrogen/fertilizer-urea",
    date: "Reviewed 2021",
    accessed: ACCESSED,
  },
  umnThreeBiggies: {
    label: "The Three Biggies: Urea, Anhydrous Ammonia, and UAN",
    publisher: "University of Minnesota Extension",
    url: "https://blog-crop-news.extension.umn.edu/2016/05/the-three-biggies-urea-anhydrous.html",
    date: "May 2016",
    accessed: ACCESSED,
  },
  msuNitrogenForms: {
    label: "Selecting forms of nitrogen fertilizer",
    publisher: "Michigan State University Extension",
    url: "https://www.canr.msu.edu/field_crops/uploads/archive/Selecting%20forms%20of%20nitrogen%20fertilizer.pdf",
    accessed: ACCESSED,
  },
  msuNitrogenSources: {
    label: "A quick look at the nitrogen cycle and nitrogen fertilizer sources — Part 2",
    publisher: "Michigan State University Extension",
    url: "https://www.canr.msu.edu/news/nitrogen_cycle_and_nitrogen_fertilizer_sources_part_2",
    date: "February 2017",
    accessed: ACCESSED,
  },
} satisfies Record<string, Source>;

function crumb(name: string, path: string) {
  return { name, path };
}

const HOME_CRUMB = crumb("Home", "/");
const RESOURCES_CRUMB = crumb("Resources", "/resources");

export const CONTENT_PAGES: ContentPage[] = [
  {
    slug: "/guides/how-to-compare-fertilizer-quotes",
    section: "guide",
    title: "How to Compare Fertilizer Quotes (Step by Step) — FertaFind",
    h1: "How to compare fertilizer quotes",
    description:
      "A plain-language method for comparing fertilizer quotes on the same basis: cost per pound of actual nutrient, delivered to your farm. Includes formulas and a worked example.",
    ogTitle: "How to compare fertilizer quotes",
    ogDescription:
      "Put every fertilizer quote on the same basis — cost per pound of nutrient, delivered — with formulas and a worked example.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [
      HOME_CRUMB,
      RESOURCES_CRUMB,
      crumb("How to compare fertilizer quotes", "/guides/how-to-compare-fertilizer-quotes"),
    ],
    sources: [SRC.ersFup, SRC.amsMarketNews, SRC.umnPhosphorus, SRC.umnUrea],
  },
  {
    slug: "/guides/fertilizer-cost-per-acre",
    section: "guide",
    title: "How to Calculate Fertilizer Cost Per Acre — FertaFind",
    h1: "How to calculate fertilizer cost per acre",
    description:
      "How to turn a fertilizer price and a planned application rate into a cost per acre, with the formula, a worked example, and where freight fits in.",
    ogTitle: "Fertilizer cost per acre",
    ogDescription:
      "Turn a fertilizer price and a planned rate into a cost-per-acre figure — formula and worked example.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [
      HOME_CRUMB,
      RESOURCES_CRUMB,
      crumb("Fertilizer cost per acre", "/guides/fertilizer-cost-per-acre"),
    ],
    sources: [SRC.ersFup, SRC.amsMarketNews],
  },
  {
    slug: "/guides/cost-per-pound-of-nitrogen",
    section: "guide",
    title: "How to Calculate Cost Per Pound of Nitrogen — FertaFind",
    h1: "How to calculate cost per pound of nitrogen",
    description:
      "Compare nitrogen fertilizers fairly by converting price per ton or gallon into cost per pound of actual nitrogen. Includes the formula and a comparison table.",
    ogTitle: "Cost per pound of nitrogen",
    ogDescription:
      "Convert fertilizer price into cost per pound of actual nitrogen so you can compare urea, UAN and other sources.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [
      HOME_CRUMB,
      RESOURCES_CRUMB,
      crumb("Cost per pound of nitrogen", "/guides/cost-per-pound-of-nitrogen"),
    ],
    sources: [
      SRC.umnUrea,
      SRC.umnThreeBiggies,
      SRC.msuNitrogenSources,
      SRC.ersFup,
      SRC.amsMarketNews,
    ],
  },
  {
    slug: "/guides/how-freight-affects-fertilizer-cost",
    section: "guide",
    title: "How Freight Affects Your Real Fertilizer Cost — FertaFind",
    h1: "How freight affects your real fertilizer cost",
    description:
      "Why the delivered (landed) cost — plant price plus freight to your farm — is the number that decides which fertilizer quote is really cheapest. Includes a worked example.",
    ogTitle: "How freight affects fertilizer cost",
    ogDescription:
      "The delivered cost — plant price plus freight — decides which quote is really cheapest. Worked example inside.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [
      HOME_CRUMB,
      RESOURCES_CRUMB,
      crumb("How freight affects fertilizer cost", "/guides/how-freight-affects-fertilizer-cost"),
    ],
    sources: [SRC.amsMarketNews, SRC.amsPricing, SRC.ersFup],
  },
  {
    slug: "/compare/dap-vs-map",
    section: "comparison",
    title: "DAP vs MAP: How the Two Phosphate Fertilizers Compare — FertaFind",
    h1: "DAP vs MAP: comparing two phosphate fertilizers",
    description:
      "DAP is 18-46-0 and MAP is 11-52-0. How the two phosphate fertilizers differ, how to compare them on cost per pound of P2O5, and what the difference does — and does not — change.",
    ogTitle: "DAP vs MAP",
    ogDescription:
      "DAP (18-46-0) vs MAP (11-52-0): the real differences and how to compare them on cost per pound of phosphate.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [HOME_CRUMB, RESOURCES_CRUMB, crumb("DAP vs MAP", "/compare/dap-vs-map")],
    sources: [SRC.umnPhosphorus, SRC.umnPhosphorusBlog],
  },
  {
    slug: "/compare/urea-vs-uan",
    section: "comparison",
    title: "Urea vs UAN: Comparing Two Nitrogen Sources — FertaFind",
    h1: "Urea vs UAN: comparing two nitrogen sources",
    description:
      "Urea is 46-0-0 (dry) and UAN is a liquid at 28-0-0 to 32-0-0. How they compare on cost per pound of nitrogen and on handling, with the numbers you need to convert prices.",
    ogTitle: "Urea vs UAN",
    ogDescription:
      "Urea (46-0-0) vs UAN (28–32% N): how to compare them on cost per pound of nitrogen and on handling.",
    lastUpdated: "2026-07-22",
    structuredData: "Article",
    breadcrumb: [HOME_CRUMB, RESOURCES_CRUMB, crumb("Urea vs UAN", "/compare/urea-vs-uan")],
    sources: [SRC.umnUrea, SRC.umnThreeBiggies, SRC.msuNitrogenForms],
  },
  {
    slug: "/methodology/usda-ams-fertilizer-data",
    section: "methodology",
    title: "How FertaFind Uses Public USDA Fertilizer Data — FertaFind",
    h1: "How FertaFind uses public USDA fertilizer data",
    description:
      "The public USDA references behind FertaFind's price comparisons — USDA AMS Market News and USDA ERS Fertilizer Use and Price — what each one is, and the limitations of using them.",
    ogTitle: "How FertaFind uses public USDA fertilizer data",
    ogDescription:
      "The public USDA AMS and ERS fertilizer references behind our comparisons — what each is, and their limitations.",
    lastUpdated: "2026-07-22",
    structuredData: "WebPage",
    breadcrumb: [
      HOME_CRUMB,
      RESOURCES_CRUMB,
      crumb("USDA fertilizer data", "/methodology/usda-ams-fertilizer-data"),
    ],
    sources: [SRC.amsMarketNews, SRC.amsPricing, SRC.ersFup, SRC.ersFupDocs],
  },
];

/** Look up a content page by its slug. */
export function getContentPage(slug: string): ContentPage | undefined {
  return CONTENT_PAGES.find((p) => p.slug === slug);
}

// ---------------------------------------------------------------------------
// Metadata + structured data for content pages
// ---------------------------------------------------------------------------

/** Per-page head metadata (title, description, Open Graph, Twitter, canonical). */
export function contentPageMeta(page: ContentPage): {
  meta: MetaEntry[];
  links: LinkEntry[];
} {
  const url = canonicalUrl(page.slug);
  return {
    meta: [
      { title: page.title },
      { name: "description", content: page.description },
      { property: "og:title", content: page.ogTitle },
      { property: "og:description", content: page.ogDescription },
      { property: "og:url", content: url },
      { property: "og:type", content: "article" },
      { name: "twitter:title", content: page.ogTitle },
      { name: "twitter:description", content: page.ogDescription },
    ],
    links: [{ rel: "canonical", href: url }],
  };
}

/** Article or WebPage structured data (no fabricated author/rating/review). */
export function contentLd(page: ContentPage) {
  const url = canonicalUrl(page.slug);
  const publisher = {
    "@type": "Organization",
    name: SITE_NAME,
    url: `${SITE_URL}/`,
    logo: DEFAULT_OG_IMAGE,
  };
  const base = {
    "@context": "https://schema.org",
    "@type": page.structuredData,
    headline: page.h1,
    name: page.h1,
    description: page.description,
    url,
    mainEntityOfPage: url,
    inLanguage: "en",
    dateModified: page.lastUpdated,
    isPartOf: { "@type": "WebSite", name: SITE_NAME, url: `${SITE_URL}/` },
  };
  if (page.structuredData === "Article") {
    return {
      ...base,
      datePublished: page.lastUpdated,
      // Organisational authorship only — no invented person or credentials.
      author: publisher,
      publisher,
      image: DEFAULT_OG_IMAGE,
    };
  }
  return { ...base, publisher };
}

/** Complete route `head()` for a content page: metadata + Article/WebPage + BreadcrumbList. */
export function contentRouteHead(page: ContentPage) {
  const base = contentPageMeta(page);
  const englishUrl = `${SITE_URL}${localePath(DEFAULT_LOCALE, page.slug)}`;
  return {
    ...base,
    // English-only body: canonical always points at the English URL and NO pt-BR alternate is
    // advertised, so a Portuguese visitor is never served an English page labelled Portuguese.
    links: [
      ...(base.links ?? []).filter((l) => l.rel !== "canonical"),
      { rel: "canonical", href: englishUrl },
      { rel: "alternate", href: englishUrl, hrefLang: "x-default" },
    ],
    scripts: [jsonLdScript(contentLd(page)), jsonLdScript(breadcrumbLd(page.breadcrumb))],
  };
}

// ---------------------------------------------------------------------------
// /resources — the indexable hub that lists every content page.
// ---------------------------------------------------------------------------
export const RESOURCES = {
  path: "/resources",
  title: "Fertilizer Pricing Guides & Comparisons — FertaFind",
  description:
    "Plain-language guides and comparisons for putting fertilizer quotes on the same basis: cost per pound of nutrient, cost per acre, freight, DAP vs MAP, urea vs UAN, and the public data behind it.",
  ogTitle: "FertaFind resources",
  ogDescription: "Guides and comparisons for comparing fertilizer prices on the same cost basis.",
  lastUpdated: "2026-07-22",
};

export function resourcesCollectionLd() {
  const url = canonicalUrl(RESOURCES.path);
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: RESOURCES.ogTitle,
    description: RESOURCES.description,
    url,
    inLanguage: "en",
    isPartOf: { "@type": "WebSite", name: SITE_NAME, url: `${SITE_URL}/` },
    hasPart: CONTENT_PAGES.map((p) => ({
      "@type": p.structuredData,
      name: p.h1,
      url: canonicalUrl(p.slug),
    })),
  };
}

export function resourcesRouteHead(locale: Locale = DEFAULT_LOCALE) {
  return {
    ...localizedHead(locale, "resources", RESOURCES.path),
    scripts: [
      jsonLdScript(resourcesCollectionLd()),
      jsonLdScript(
        breadcrumbLd([
          { name: "Home", path: "/" },
          { name: "Resources", path: "/resources" },
        ]),
      ),
    ],
  };
}

// ---------------------------------------------------------------------------
// Sitemap — generated from this registry plus the core pages in seo.ts.
// public/sitemap.xml must equal buildSitemapXml() (enforced by tests), so the
// registry is the single source of truth and future pages cannot drift.
// ---------------------------------------------------------------------------

/**
 * The bare (locale-less) indexable paths. Excludes /results, which is noindex.
 *
 * `englishOnly` marks long-form editorial whose body has NOT been translated. Those pages
 * are published in English only: no pt-BR sitemap entry and no pt-BR hreflang alternate, so
 * we never advertise a Portuguese page that is really English.
 */
function basePaths(): Array<{ path: string; priority: string; englishOnly?: boolean }> {
  return [
    { path: PAGES.home.path, priority: "1.0" },
    { path: PAGES.analyze.path, priority: "0.8" },
    { path: "/suppliers", priority: "0.7" },
    { path: "/resources", priority: "0.7" },
    ...CONTENT_PAGES.map((p) => ({ path: p.slug, priority: "0.6", englishOnly: true })),
    ...publicSupplierSlugs().map((slug) => ({ path: supplierPath(slug), priority: "0.5" })),
    { path: PAGES.terms.path, priority: "0.4" },
  ];
}

/** True when a path's body is English-only and must not be advertised in other locales. */
export function isEnglishOnlyPath(path: string): boolean {
  return basePaths().some((e) => e.path === path && e.englishOnly === true);
}

/** Paths published in every locale. */
export function localizedPaths(): string[] {
  return basePaths()
    .filter((e) => !e.englishOnly)
    .map((e) => e.path);
}

/**
 * Ordered indexable paths with sitemap priorities — every page once PER LOCALE, so each
 * language has its own indexable URL and the hreflang cluster is complete.
 */
export function sitemapEntries(): Array<{ path: string; priority: string }> {
  return basePaths().flatMap((entry) => {
    const locales = entry.englishOnly ? [DEFAULT_LOCALE] : SUPPORTED_LOCALES;
    return locales.map((locale) => ({
      path: localePath(locale, entry.path),
      priority: entry.priority,
    }));
  });
}

/** Every indexable bare path (one per page, locale-independent). */
export function allIndexablePaths(): string[] {
  return basePaths().map((e) => e.path);
}

/** Deterministic sitemap XML built from the registry. */
export function buildSitemapXml(): string {
  const urls = sitemapEntries()
    .map(
      (e) =>
        `  <url>\n    <loc>${canonicalUrl(e.path)}</loc>\n    <priority>${e.priority}</priority>\n  </url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

/** Display helper: ISO date -> "July 22, 2026". */
export function formatDate(iso: string): string {
  const [y, m, d] = iso.split("-").map((n) => parseInt(n, 10));
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  if (!y || !m || !d || m < 1 || m > 12) return iso;
  return `${months[m - 1]} ${d}, ${y}`;
}
