/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SupplierPortalRouteImport } from './routes/supplier-portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as ApiWeatherRouteImport } from './routes/api.weather'
import { Route as ApiReverseGeocodeRouteImport } from './routes/api.reverse-geocode'
import { Route as ApiNearbySuppliersRouteImport } from './routes/api.nearby-suppliers'
import { Route as ApiGeocodeRouteImport } from './routes/api.geocode'
import { Route as ApiAnalyzeQuotesRouteImport } from './routes/api.analyze-quotes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPortalRoute = SupplierPortalRouteImport.update({
  id: '/supplier-portal',
  path: '/supplier-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverseGeocodeRoute = ApiReverseGeocodeRouteImport.update({
  id: '/api/reverse-geocode',
  path: '/api/reverse-geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearbySuppliersRoute = ApiNearbySuppliersRouteImport.update({
  id: '/api/nearby-suppliers',
  path: '/api/nearby-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeQuotesRoute = ApiAnalyzeQuotesRouteImport.update({
  id: '/api/analyze-quotes',
  path: '/api/analyze-quotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/partners': typeof PartnersRoute
  '/supplier-portal': typeof SupplierPortalRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/partners': typeof PartnersRoute
  '/supplier-portal': typeof SupplierPortalRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/partners': typeof PartnersRoute
  '/supplier-portal': typeof SupplierPortalRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/partners'
    | '/supplier-portal'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/partners'
    | '/supplier-portal'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/analyze'
    | '/partners'
    | '/supplier-portal'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AnalyzeRoute: typeof AnalyzeRoute
  PartnersRoute: typeof PartnersRoute
  SupplierPortalRoute: typeof SupplierPortalRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  ApiAnalyzeQuotesRoute: typeof ApiAnalyzeQuotesRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiNearbySuppliersRoute: typeof ApiNearbySuppliersRoute
  ApiReverseGeocodeRoute: typeof ApiReverseGeocodeRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal': {
      id: '/supplier-portal'
      path: '/supplier-portal'
      fullPath: '/supplier-portal'
      preLoaderRoute: typeof SupplierPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverse-geocode': {
      id: '/api/reverse-geocode'
      path: '/api/reverse-geocode'
      fullPath: '/api/reverse-geocode'
      preLoaderRoute: typeof ApiReverseGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearby-suppliers': {
      id: '/api/nearby-suppliers'
      path: '/api/nearby-suppliers'
      fullPath: '/api/nearby-suppliers'
      preLoaderRoute: typeof ApiNearbySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-quotes': {
      id: '/api/analyze-quotes'
      path: '/api/analyze-quotes'
      fullPath: '/api/analyze-quotes'
      preLoaderRoute: typeof ApiAnalyzeQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AnalyzeRoute: AnalyzeRoute,
  PartnersRoute: PartnersRoute,
  SupplierPortalRoute: SupplierPortalRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  ApiAnalyzeQuotesRoute: ApiAnalyzeQuotesRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiNearbySuppliersRoute: ApiNearbySuppliersRoute,
  ApiReverseGeocodeRoute: ApiReverseGeocodeRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
