/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as MethodologyUsdaAmsFertilizerDataRouteImport } from './routes/methodology.usda-ams-fertilizer-data'
import { Route as GuidesHowToCompareFertilizerQuotesRouteImport } from './routes/guides.how-to-compare-fertilizer-quotes'
import { Route as GuidesHowFreightAffectsFertilizerCostRouteImport } from './routes/guides.how-freight-affects-fertilizer-cost'
import { Route as GuidesFertilizerCostPerAcreRouteImport } from './routes/guides.fertilizer-cost-per-acre'
import { Route as GuidesCostPerPoundOfNitrogenRouteImport } from './routes/guides.cost-per-pound-of-nitrogen'
import { Route as CompareUreaVsUanRouteImport } from './routes/compare.urea-vs-uan'
import { Route as CompareDapVsMapRouteImport } from './routes/compare.dap-vs-map'
import { Route as ApiWeatherRouteImport } from './routes/api.weather'
import { Route as ApiReverseGeocodeRouteImport } from './routes/api.reverse-geocode'
import { Route as ApiNearbySuppliersRouteImport } from './routes/api.nearby-suppliers'
import { Route as ApiGeocodeRouteImport } from './routes/api.geocode'
import { Route as ApiExtractSoilTestRouteImport } from './routes/api.extract-soil-test'
import { Route as ApiAnalyzeQuotesRouteImport } from './routes/api.analyze-quotes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyUsdaAmsFertilizerDataRoute =
  MethodologyUsdaAmsFertilizerDataRouteImport.update({
    id: '/methodology/usda-ams-fertilizer-data',
    path: '/methodology/usda-ams-fertilizer-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowToCompareFertilizerQuotesRoute =
  GuidesHowToCompareFertilizerQuotesRouteImport.update({
    id: '/guides/how-to-compare-fertilizer-quotes',
    path: '/guides/how-to-compare-fertilizer-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesHowFreightAffectsFertilizerCostRoute =
  GuidesHowFreightAffectsFertilizerCostRouteImport.update({
    id: '/guides/how-freight-affects-fertilizer-cost',
    path: '/guides/how-freight-affects-fertilizer-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesFertilizerCostPerAcreRoute =
  GuidesFertilizerCostPerAcreRouteImport.update({
    id: '/guides/fertilizer-cost-per-acre',
    path: '/guides/fertilizer-cost-per-acre',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesCostPerPoundOfNitrogenRoute =
  GuidesCostPerPoundOfNitrogenRouteImport.update({
    id: '/guides/cost-per-pound-of-nitrogen',
    path: '/guides/cost-per-pound-of-nitrogen',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareUreaVsUanRoute = CompareUreaVsUanRouteImport.update({
  id: '/compare/urea-vs-uan',
  path: '/compare/urea-vs-uan',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareDapVsMapRoute = CompareDapVsMapRouteImport.update({
  id: '/compare/dap-vs-map',
  path: '/compare/dap-vs-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReverseGeocodeRoute = ApiReverseGeocodeRouteImport.update({
  id: '/api/reverse-geocode',
  path: '/api/reverse-geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNearbySuppliersRoute = ApiNearbySuppliersRouteImport.update({
  id: '/api/nearby-suppliers',
  path: '/api/nearby-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractSoilTestRoute = ApiExtractSoilTestRouteImport.update({
  id: '/api/extract-soil-test',
  path: '/api/extract-soil-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeQuotesRoute = ApiAnalyzeQuotesRouteImport.update({
  id: '/api/analyze-quotes',
  path: '/api/analyze-quotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/resources': typeof ResourcesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/extract-soil-test': typeof ApiExtractSoilTestRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/compare/dap-vs-map': typeof CompareDapVsMapRoute
  '/compare/urea-vs-uan': typeof CompareUreaVsUanRoute
  '/guides/cost-per-pound-of-nitrogen': typeof GuidesCostPerPoundOfNitrogenRoute
  '/guides/fertilizer-cost-per-acre': typeof GuidesFertilizerCostPerAcreRoute
  '/guides/how-freight-affects-fertilizer-cost': typeof GuidesHowFreightAffectsFertilizerCostRoute
  '/guides/how-to-compare-fertilizer-quotes': typeof GuidesHowToCompareFertilizerQuotesRoute
  '/methodology/usda-ams-fertilizer-data': typeof MethodologyUsdaAmsFertilizerDataRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/resources': typeof ResourcesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/extract-soil-test': typeof ApiExtractSoilTestRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/compare/dap-vs-map': typeof CompareDapVsMapRoute
  '/compare/urea-vs-uan': typeof CompareUreaVsUanRoute
  '/guides/cost-per-pound-of-nitrogen': typeof GuidesCostPerPoundOfNitrogenRoute
  '/guides/fertilizer-cost-per-acre': typeof GuidesFertilizerCostPerAcreRoute
  '/guides/how-freight-affects-fertilizer-cost': typeof GuidesHowFreightAffectsFertilizerCostRoute
  '/guides/how-to-compare-fertilizer-quotes': typeof GuidesHowToCompareFertilizerQuotesRoute
  '/methodology/usda-ams-fertilizer-data': typeof MethodologyUsdaAmsFertilizerDataRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyze': typeof AnalyzeRoute
  '/resources': typeof ResourcesRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/api/analyze-quotes': typeof ApiAnalyzeQuotesRoute
  '/api/extract-soil-test': typeof ApiExtractSoilTestRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/nearby-suppliers': typeof ApiNearbySuppliersRoute
  '/api/reverse-geocode': typeof ApiReverseGeocodeRoute
  '/api/weather': typeof ApiWeatherRoute
  '/compare/dap-vs-map': typeof CompareDapVsMapRoute
  '/compare/urea-vs-uan': typeof CompareUreaVsUanRoute
  '/guides/cost-per-pound-of-nitrogen': typeof GuidesCostPerPoundOfNitrogenRoute
  '/guides/fertilizer-cost-per-acre': typeof GuidesFertilizerCostPerAcreRoute
  '/guides/how-freight-affects-fertilizer-cost': typeof GuidesHowFreightAffectsFertilizerCostRoute
  '/guides/how-to-compare-fertilizer-quotes': typeof GuidesHowToCompareFertilizerQuotesRoute
  '/methodology/usda-ams-fertilizer-data': typeof MethodologyUsdaAmsFertilizerDataRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyze'
    | '/resources'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/extract-soil-test'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/compare/dap-vs-map'
    | '/compare/urea-vs-uan'
    | '/guides/cost-per-pound-of-nitrogen'
    | '/guides/fertilizer-cost-per-acre'
    | '/guides/how-freight-affects-fertilizer-cost'
    | '/guides/how-to-compare-fertilizer-quotes'
    | '/methodology/usda-ams-fertilizer-data'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyze'
    | '/resources'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/extract-soil-test'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/compare/dap-vs-map'
    | '/compare/urea-vs-uan'
    | '/guides/cost-per-pound-of-nitrogen'
    | '/guides/fertilizer-cost-per-acre'
    | '/guides/how-freight-affects-fertilizer-cost'
    | '/guides/how-to-compare-fertilizer-quotes'
    | '/methodology/usda-ams-fertilizer-data'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyze'
    | '/resources'
    | '/suppliers'
    | '/terms'
    | '/api/analyze-quotes'
    | '/api/extract-soil-test'
    | '/api/geocode'
    | '/api/nearby-suppliers'
    | '/api/reverse-geocode'
    | '/api/weather'
    | '/compare/dap-vs-map'
    | '/compare/urea-vs-uan'
    | '/guides/cost-per-pound-of-nitrogen'
    | '/guides/fertilizer-cost-per-acre'
    | '/guides/how-freight-affects-fertilizer-cost'
    | '/guides/how-to-compare-fertilizer-quotes'
    | '/methodology/usda-ams-fertilizer-data'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ResourcesRoute: typeof ResourcesRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  ApiAnalyzeQuotesRoute: typeof ApiAnalyzeQuotesRoute
  ApiExtractSoilTestRoute: typeof ApiExtractSoilTestRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiNearbySuppliersRoute: typeof ApiNearbySuppliersRoute
  ApiReverseGeocodeRoute: typeof ApiReverseGeocodeRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  CompareDapVsMapRoute: typeof CompareDapVsMapRoute
  CompareUreaVsUanRoute: typeof CompareUreaVsUanRoute
  GuidesCostPerPoundOfNitrogenRoute: typeof GuidesCostPerPoundOfNitrogenRoute
  GuidesFertilizerCostPerAcreRoute: typeof GuidesFertilizerCostPerAcreRoute
  GuidesHowFreightAffectsFertilizerCostRoute: typeof GuidesHowFreightAffectsFertilizerCostRoute
  GuidesHowToCompareFertilizerQuotesRoute: typeof GuidesHowToCompareFertilizerQuotesRoute
  MethodologyUsdaAmsFertilizerDataRoute: typeof MethodologyUsdaAmsFertilizerDataRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology/usda-ams-fertilizer-data': {
      id: '/methodology/usda-ams-fertilizer-data'
      path: '/methodology/usda-ams-fertilizer-data'
      fullPath: '/methodology/usda-ams-fertilizer-data'
      preLoaderRoute: typeof MethodologyUsdaAmsFertilizerDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-compare-fertilizer-quotes': {
      id: '/guides/how-to-compare-fertilizer-quotes'
      path: '/guides/how-to-compare-fertilizer-quotes'
      fullPath: '/guides/how-to-compare-fertilizer-quotes'
      preLoaderRoute: typeof GuidesHowToCompareFertilizerQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-freight-affects-fertilizer-cost': {
      id: '/guides/how-freight-affects-fertilizer-cost'
      path: '/guides/how-freight-affects-fertilizer-cost'
      fullPath: '/guides/how-freight-affects-fertilizer-cost'
      preLoaderRoute: typeof GuidesHowFreightAffectsFertilizerCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/fertilizer-cost-per-acre': {
      id: '/guides/fertilizer-cost-per-acre'
      path: '/guides/fertilizer-cost-per-acre'
      fullPath: '/guides/fertilizer-cost-per-acre'
      preLoaderRoute: typeof GuidesFertilizerCostPerAcreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cost-per-pound-of-nitrogen': {
      id: '/guides/cost-per-pound-of-nitrogen'
      path: '/guides/cost-per-pound-of-nitrogen'
      fullPath: '/guides/cost-per-pound-of-nitrogen'
      preLoaderRoute: typeof GuidesCostPerPoundOfNitrogenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/urea-vs-uan': {
      id: '/compare/urea-vs-uan'
      path: '/compare/urea-vs-uan'
      fullPath: '/compare/urea-vs-uan'
      preLoaderRoute: typeof CompareUreaVsUanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/dap-vs-map': {
      id: '/compare/dap-vs-map'
      path: '/compare/dap-vs-map'
      fullPath: '/compare/dap-vs-map'
      preLoaderRoute: typeof CompareDapVsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reverse-geocode': {
      id: '/api/reverse-geocode'
      path: '/api/reverse-geocode'
      fullPath: '/api/reverse-geocode'
      preLoaderRoute: typeof ApiReverseGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nearby-suppliers': {
      id: '/api/nearby-suppliers'
      path: '/api/nearby-suppliers'
      fullPath: '/api/nearby-suppliers'
      preLoaderRoute: typeof ApiNearbySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-soil-test': {
      id: '/api/extract-soil-test'
      path: '/api/extract-soil-test'
      fullPath: '/api/extract-soil-test'
      preLoaderRoute: typeof ApiExtractSoilTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-quotes': {
      id: '/api/analyze-quotes'
      path: '/api/analyze-quotes'
      fullPath: '/api/analyze-quotes'
      preLoaderRoute: typeof ApiAnalyzeQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzeRoute: AnalyzeRoute,
  ResourcesRoute: ResourcesRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  ApiAnalyzeQuotesRoute: ApiAnalyzeQuotesRoute,
  ApiExtractSoilTestRoute: ApiExtractSoilTestRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiNearbySuppliersRoute: ApiNearbySuppliersRoute,
  ApiReverseGeocodeRoute: ApiReverseGeocodeRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  CompareDapVsMapRoute: CompareDapVsMapRoute,
  CompareUreaVsUanRoute: CompareUreaVsUanRoute,
  GuidesCostPerPoundOfNitrogenRoute: GuidesCostPerPoundOfNitrogenRoute,
  GuidesFertilizerCostPerAcreRoute: GuidesFertilizerCostPerAcreRoute,
  GuidesHowFreightAffectsFertilizerCostRoute:
    GuidesHowFreightAffectsFertilizerCostRoute,
  GuidesHowToCompareFertilizerQuotesRoute:
    GuidesHowToCompareFertilizerQuotesRoute,
  MethodologyUsdaAmsFertilizerDataRoute: MethodologyUsdaAmsFertilizerDataRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
