-- Records the terms version accepted during account creation.
-- Acceptance rows are append-only from the browser: users can insert and read their own records,
-- but cannot update or delete them.
create table if not exists public.terms_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  acceptance_method text not null check (acceptance_method in ('password', 'google')),
  accepted_at timestamptz not null default now(),
  unique (user_id, terms_version)
);

alter table public.terms_acceptances enable row level security;

create policy "users view their terms acceptances"
  on public.terms_acceptances for select
  using (auth.uid() = user_id);

create policy "users record their terms acceptance"
  on public.terms_acceptances for insert
  with check (auth.uid() = user_id);
